"""Changed message to content in messages table

Revision ID: d06efdfa9460
Revises: ced95444205e
Create Date: 2025-10-24 14:48:42.044293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd06efdfa9460'
down_revision: Union[str, Sequence[str], None] = 'ced95444205e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('content', sa.String(), nullable=False))
    op.drop_column('messages', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('messages', 'content')
    # ### end Alembic commands ###
